import assert from "node:assert/strict";import {test} from "node:test";import {enqueueReplyAlert,listReplyAlerts,acknowledgeReplyAlert,markReplyResponded,closeReplyCase,replySlaLevel} from "../reply-alerts-v1.mjs";
function memfs(){const m=new Map();return{m,readFile:async p=>{if(!m.has(p))throw Object.assign(new Error("x"),{code:"ENOENT"});return m.get(p)},mkdir:async()=>{},writeFile:async(p,v)=>m.set(p,String(v)),rename:async(a,b)=>{m.set(b,m.get(a));m.delete(a)},chmod:async()=>{}}}
const T0=new Date("2026-10-02T10:00:00Z");
const event={emailId:"e1",type:"human_reply",prospectId:"124",publisher:"P",receivedAt:"2026-10-02T09:30:00",subject:"s"};
test("human reply case is durable and deduplicated",async()=>{const f=memfs(),p="/x/a.json";assert.equal((await enqueueReplyAlert(event,{fsImpl:f,alertPath:p,now:T0})).added,true);assert.equal((await enqueueReplyAlert(event,{fsImpl:f,alertPath:p,now:T0})).added,false);const a=await listReplyAlerts({fsImpl:f,alertPath:p,now:T0,all:true});assert.equal(a.length,1);assert.equal(a[0].status,"pending_response");assert.equal(a[0].slaLevel,"initial");});
test("ack records alert level but keeps response case open",async()=>{const f=memfs(),p="/x/a.json";await enqueueReplyAlert(event,{fsImpl:f,alertPath:p,now:T0});const r=await acknowledgeReplyAlert("e1",{fsImpl:f,alertPath:p,now:T0});assert.equal(r.acked,true);assert.equal(r.level,"initial");assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:T0})).length,0);assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:T0,all:true})).length,1);});
test("SLA escalates once per level",async()=>{const f=memfs(),p="/x/a.json";await enqueueReplyAlert(event,{fsImpl:f,alertPath:p,now:T0});await acknowledgeReplyAlert("e1",{fsImpl:f,alertPath:p,now:T0});const t5=new Date("2026-10-02T14:30:01Z"),t13=new Date("2026-10-02T22:30:01Z"),t25=new Date("2026-10-03T10:30:01Z");assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:t5}))[0].slaLevel,"reminder_4h");await acknowledgeReplyAlert("e1",{fsImpl:f,alertPath:p,now:t5});assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:t13}))[0].slaLevel,"urgent_12h");await acknowledgeReplyAlert("e1",{fsImpl:f,alertPath:p,now:t13});assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:t25}))[0].slaLevel,"critical_24h");});
test("responded and closed stop SLA alerts",async()=>{const f=memfs(),p="/x/a.json";await enqueueReplyAlert(event,{fsImpl:f,alertPath:p,now:T0});assert.equal((await markReplyResponded("e1",{fsImpl:f,alertPath:p,now:T0})).updated,true);assert.equal((await listReplyAlerts({fsImpl:f,alertPath:p,now:new Date("2026-10-04T00:00:00Z")})).length,0);assert.equal((await closeReplyCase("e1",{fsImpl:f,alertPath:p,now:T0})).updated,true);});
test("legacy v1 item without SLA fields is normalized",async()=>{const f=memfs(),p="/x/a.json";f.m.set(p,JSON.stringify({version:1,pending:[{emailId:"old",prospectId:"1",publisher:"Old",receivedAt:"2026-10-01T00:00:00",subject:"x"}]}));const a=await listReplyAlerts({fsImpl:f,alertPath:p,now:T0,all:true});assert.equal(a[0].status,"pending_response");assert.deepEqual(a[0].alertedLevels,[]);assert.equal(replySlaLevel(a[0],T0),"critical_24h");});
